# Generated by Django 3.1.5 on 2022-12-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20221210_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnot_likes',
            name='Dnot_like',
        ),
        migrations.AddField(
            model_name='dnot_likes',
            name='dnot_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_images/default_news.jpg', upload_to='news_images/'),
        ),
    ]
